name: CI - Build and Test Docker Image


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted


    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to Remote Server (.140)
        run: |
          rsync -avz --exclude '.git' . root@192.168.10.140:/home/naron1/ai-sentiment-lab-2
          ssh root@192.168.10.140 "cd /home/naron1/ai-sentiment-lab-2 && sudo docker-compose up -d --build"